baseURL = "https://www.zhaoqingxu.com/"
locale = "en-us"
title = "Zhaoqing Xu | Computational Mathematics"
theme = "PaperMod"

[params]
  env = "production"
  author = "Zhaoqing Xu"
  description = "Ph.D. Candidate in Computational Mathematics at University of South Carolina"
  math = true
  defaultTheme = "light"
  images = ["og-card.png"]
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowShareButtons = false

[params.assets]
  theme_color = "#f5f8fa"
  msapplication_TileColor = "#f5f8fa"

[params.profileMode]
  enabled = false

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "Research"
  url = "/research/"
  weight = 2

[[menu.main]]
  name = "Teaching"
  url = "/teaching/"
  weight = 3

[[menu.main]]
  name = "Musings"
  url = "/notes/"
  weight = 4

[[menu.main]]
  name = "CV"
  url = "/cv.pdf"
  weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2